name: hyperbolo_film

input:
  adjacency: all
  main_dir: /mnt/storage/speos/
  save_dir: /mnt/storage/speos/data/

model:
  hyperbolic: 
    switch: on
    manifold: PoincareBall
  pre_mp:
    n_layers: 1
    dim: 20
  mp:
    type: HFiLMConv
    dim: 20
    kwargs:
      local_agg: False
      c_per_relation: True
    n_layers: 2
    act: Identity
  post_mp:
    n_layers: 1
    dim: 20
  save_dir: /mnt/storage/speos/models/
  plot_dir: /mnt/storage/speos/plots/

logging:
  dir: /mnt/storage/speos/logs/

inference:
  save_dir: /mnt/storage/speos/results/

pp:
  save_dir: /mnt/storage/speos/results/
  plot_dir: /mnt/storage/speos/plots/

optim:
  lr: 0.01