name: immune_dysregulation_tag
input:
  tag: Immune_Dysregulation
  adjacency: IntAct_Direct

crossval:
  mode: kfold         # None, kfold, holdoneout (not implemented)
  n_folds: 10
  positive_only: True

model:
  save_dir: models/
  plot_dir: plots/
  pre_mp:
    n_layers: 2
  mp:
    n_layers: 2
    type: tag
  post_mp:
    n_layers: 2

logging:
  dir: logs/

inference:
  save_dir: results/
  save_tsv: True

pp:
  save_dir: results/
  plot_dir: plots/