from speos.tests.test_companions import CompanionTest
from speos.tests.test_config import *
from speos.tests.test_crossval import *
from speos.tests.test_datahandler import *
from speos.tests.test_dataset import *
from speos.tests.test_functional import *
from speos.tests.test_inference import *
from speos.tests.test_logging import *
from speos.tests.test_inference import *
from speos.tests.test_logging import *
from speos.tests.test_losses import *
from speos.tests.test_metrics import *
from speos.tests.test_models import *
from speos.tests.test_postprocessor import *
from speos.tests.test_preprocessor import *
from speos.tests.test_graphdiagnostic import *
from speos.tests.test_testbench import *
from speos.tests.test_layers import *
from speos.tests.test_adjacencies import *
from speos.tests.test_explanations import *