name: hyperbolo_bioplex_logal_agg

input:
  main_dir: /mnt/storage/speos/
  save_dir: /mnt/storage/speos/data/

model:
  hyperbolic: 
    switch: on
    manifold: PoincareBall
  pre_mp:
    n_layers: 1
    dim: 10
  mp:
    type: HGCNConv
    dim: 10
    kwargs:
      local_agg: True
      use_att: False
    n_layers: 2
  post_mp:
    n_layers: 1
    dim: 10
  save_dir: /mnt/storage/speos/models/
  plot_dir: /mnt/storage/speos/plots/

logging:
  dir: /mnt/storage/speos/logs/

inference:
  save_dir: /mnt/storage/speos/results/

pp:
  save_dir: /mnt/storage/speos/results/
  plot_dir: /mnt/storage/speos/plots/

optim:
  lr: 0.01